import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const base=process.env.PREVIEW_URL || 'http://localhost:4321';
const b=await chromium.launch({channel:'chrome',headless:true});
const context=await b.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
const p=await context.newPage();
await p.goto(base+'/');await p.waitForTimeout(1100);
assert.equal(await p.locator('.workspace-boot').count(),0);
await p.reload();assert.equal(await p.locator('.workspace-boot').count(),0);
await p.locator('.mobile-navigation [data-nav=projects]').click();
assert.equal(await p.locator('#projects').isVisible(),true);
const swipe=async selector=>{await p.locator(selector).evaluate(el=>{el.dispatchEvent(new TouchEvent('touchstart',{bubbles:true,touches:[new Touch({identifier:1,target:el,clientX:300,clientY:200})]}));el.dispatchEvent(new TouchEvent('touchend',{bubbles:true,changedTouches:[new Touch({identifier:1,target:el,clientX:80,clientY:205})]}));});};
await swipe('.explorer-detail');assert.match(await p.locator('.project-preview-heading').innerText(),/ServiceFlow/);
await p.locator('[data-open-command]').click();await p.locator('.command-dialog input').fill('testimonials');await p.keyboard.press('Enter');
await swipe('[data-testimonials]');assert.equal(await p.locator('.feedback-slide:visible cite').innerText(),'Acerbox Builds');
await p.locator('.mobile-navigation [data-nav=contact]').click();assert.equal(await p.locator('#contact-form button[type=submit]').isEnabled(),true);
await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0);
const nojs=await b.newContext({javaScriptEnabled:false});const n=await nojs.newPage();await n.goto(base+'/');assert.equal(await n.locator('.feedback-slide').count(),3);assert.equal(await n.locator('#contact-form button[type=submit]').isDisabled(),true);assert.equal(await n.locator('.fallback-navigation').isVisible(),true);
console.log('PASS touch swipe, mobile navigation, returning session intro, reduced motion, no-JS content and safe form fallback.');
await b.close();
